version: 2
jobs:
  build:
    docker:
      - image: bdadamas24/node-xvfb
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: 'npm install'
      - run:
          name: test
          command: 'xvfb-run --server-args="-screen 0 1024x768x24" npm test'
